name: CooksMap
main: de.radicarlprogramming.minecraft.cooksmap.CooksMapPlugin
author: Carl Volhard
version: 0.1
commands:
    cmap:
        description: Shows the Help for CooksMap.
        usage: |
            /<command> list (([<>][idcn]) | ([idcn][<>=!~].+))* <page>? -> list
            /<command> n -> show next page of last search
            /<command> p -> show previous page of last search
            /<command> goto <page> -> show page <page> of last search
            /<command> add (+|-)? <category> <name> -> add current position
            /<command> set <id> -> set landmark as new target
            /<command> dist -> show distance to current target
            /<command> edit <id> (v=(+|-)|c=<category>|n=<name>)+ -> change landmark
            /<command> del <id> -> delete landmark
            /<command> help <Command> -> show help for Command
      
permissions:
    cmap.*:
        default: true
        description: Allows use of all CooksMap commands.
        children:
            cmap.set: true
            cmap.add: true
            cmap.list: true
            cmap.n: true
            cmap.p: true
            cmap.goto: true
            cmap.rm: true
            cmap.dist: true
            cmap.edit: true
            cmap.help: true
    cmap.set:
        description: Allows player to sets location with the given id as compass target
        default: true
    cmap.add:
        description: Allows Player to adds current location to the map
        default: true   
    cmap.list:
        description: Allows player to list/search landmarks
        default: true 
    cmap.n:
        description: Allows player to see next page of his last search
        default: true 
    cmap.p:
        description: Allows player to see previous page of his last search
        default: true 
    cmap.goto:
        description: Allows player to see given page of his last search
        default: true 
    cmap.del:
        description: Allows player to delete own landmarks
        default: true 
    cmap.edit:
        description: Allows player to edit category, name and visibility of own landmarks
        default: true 
    cmap.dist:
        description: Allows player to see the distance to his compass target
        default: true 
    cmap.help:
        description: Allows player to see the help for a command
        default: true
        
      