name: CooksMap
main: de.radicarlprogramming.minecraft.cooksmap.CooksMapPlugin
author: Carl Volhard
version: 0.1
commands:
    cmap:
        description: Shows the Help for CooksMap.
        usage: |
            /<command> list [page]
            /<command> next
            /<command> prev
            /<command> add [public] <type> <description>
            /<command> set <id>
            /<command> dist
            /<command> rm <id>
            /<command> edit <id> [visibility=[+|-]|category=<category>|description=<description>]
      
permissions:
    cmap.*:
        default: true
        description: Allows use of all CooksMap commands.
        children:
            cmap.set: true
            cmap.add: true
            cmap.list: true
            cmap.next: true
            cmap.prev: true
            cmap.rm: true
            cmap.dist: true
            cmap.edit: true
    cmap.set:
        description: Allows player to sets location with the given id as compass target
        default: true
    cmap.add:
        description: Allows Player to adds current location to the map
        default: true   
    cmap.list:
        description: Allows player to list all landmarks
        default: true 
    cmap.next:
        description: Allows player to see next page of his last search
        default: true 
    cmap.prev:
        description: Allows player to see previous page of his last search
        default: true 
    cmap.rm:
        description: Allows player to remove own landmarks
        default: true 
    cmap.edit:
        description: Allows player to edit category, description and visibility of own landmarks
        default: true 
    cmap.dist:
        description: Allows player to see the distance to his compass target
        default: true 
        
      